// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// BF_grid_rcpp
DataFrame BF_grid_rcpp(double D, double a0, double b0, double a1, double b1, int n1, double a2, double b2, int n2, std::string model1, double da1, double db1, double dp1, std::string model2, double da2, double db2, double dp2);
RcppExport SEXP _BayesPower_BF_grid_rcpp(SEXP DSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP a1SEXP, SEXP b1SEXP, SEXP n1SEXP, SEXP a2SEXP, SEXP b2SEXP, SEXP n2SEXP, SEXP model1SEXP, SEXP da1SEXP, SEXP db1SEXP, SEXP dp1SEXP, SEXP model2SEXP, SEXP da2SEXP, SEXP db2SEXP, SEXP dp2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type D(DSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< double >::type b1(b1SEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< double >::type a2(a2SEXP);
    Rcpp::traits::input_parameter< double >::type b2(b2SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< std::string >::type model1(model1SEXP);
    Rcpp::traits::input_parameter< double >::type da1(da1SEXP);
    Rcpp::traits::input_parameter< double >::type db1(db1SEXP);
    Rcpp::traits::input_parameter< double >::type dp1(dp1SEXP);
    Rcpp::traits::input_parameter< std::string >::type model2(model2SEXP);
    Rcpp::traits::input_parameter< double >::type da2(da2SEXP);
    Rcpp::traits::input_parameter< double >::type db2(db2SEXP);
    Rcpp::traits::input_parameter< double >::type dp2(dp2SEXP);
    rcpp_result_gen = Rcpp::wrap(BF_grid_rcpp(D, a0, b0, a1, b1, n1, a2, b2, n2, model1, da1, db1, dp1, model2, da2, db2, dp2));
    return rcpp_result_gen;
END_RCPP
}
// pnct
NumericVector pnct(const NumericVector x, const double df, const NumericVector ncp, bool lower);
RcppExport SEXP _BayesPower_pnct(SEXP xSEXP, SEXP dfSEXP, SEXP ncpSEXP, SEXP lowerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type ncp(ncpSEXP);
    Rcpp::traits::input_parameter< bool >::type lower(lowerSEXP);
    rcpp_result_gen = Rcpp::wrap(pnct(x, df, ncp, lower));
    return rcpp_result_gen;
END_RCPP
}
// sum_rcpp
double sum_rcpp(NumericVector log_h1, LogicalVector PE);
RcppExport SEXP _BayesPower_sum_rcpp(SEXP log_h1SEXP, SEXP PESEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type log_h1(log_h1SEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type PE(PESEXP);
    rcpp_result_gen = Rcpp::wrap(sum_rcpp(log_h1, PE));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesPower_BF_grid_rcpp", (DL_FUNC) &_BayesPower_BF_grid_rcpp, 17},
    {"_BayesPower_pnct", (DL_FUNC) &_BayesPower_pnct, 4},
    {"_BayesPower_sum_rcpp", (DL_FUNC) &_BayesPower_sum_rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesPower(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
