#' Print Method for BFpower Objects
#'
#' Displays the results of a \code{"BFpower"} object.
#'
#' This method prints key information from the \code{"BFpower"} object,
#' including the type of hypothesis specification, priors, true and false rates,
#' and required sample. The object can be generated by any of the following functions:
#' \code{\link{BFpower.ttest.OneSample}}, \code{\link{BFpower.ttest.TwoSample}}, \code{\link{BFpower.cor}}, \code{\link{BFpower.f.test}}, \code{\link{BFpower.bin}}, or \code{\link{BFpower.props}}.
#'
#' @param x A \code{"BFpower"} object returned by one of the BFpower functions listed in the section Details.
#' @param ... Additional arguments (currently unused; included for method consistency).
#'
#' @return Invisibly returns the input \code{"BFpower"} object.
#'
#' @export
#' @method print BFpower
#'
#' @examples
#' results <- BFpower.ttest.OneSample(
#'   alternative = "two.sided",
#'   threshold = 3,
#'   true_rate = 0.8,
#'   false_rate = 0.05,
#'   prior_analysis = "t-distribution",
#'   location = 0,
#'   scale = 0.707,
#'   dff = 1
#' )
#' print(results)
print.BFpower <- function(x, ...) {

  #### Symbols
  UL <- "\u2554"; UR <- "\u2557"; LL <- "\u255a"; LR <- "\u255d"
  HL <- "\u2550"; VL <- "\u2551"; HR <- strrep(HL, 50)
  line <- paste0("\u2500", strrep("\u2500", 50), "\n")
  digits <- 3

  # Subscripts
  sub0 <- "\u2080"; sub1 <- "\u2081"; sub2 <- "\u2082"
  H0 <- paste0("H", sub0); H1 <- paste0("H", sub1)
  delta <- "\u03b4"; rho <- "\u03c1"; f2 <- "f\u00B2"; theta <- "\u03b8"
  neq <- "\u2260"; leq <- "\u2264"; union <- "\u222a"

  # Effect size symbol
  effect_size <- switch(x$type,
                        "One-sample t-test" = delta,
                        "Independent-samples t-test (equal variance)" = delta,
                        "Correlation" = rho,
                        "Regression/ANOVA" = f2,
                        "One proportion" = theta,
                        "Two-proportions" = 0)

  # Centered header
  header_text <- ifelse(x$mode_bf == 1, "SAMPLE SIZE CALCULATION", "POWER CALCULATION")
  pad_total <- 50 - nchar(header_text)
  pad_left <- floor(pad_total / 2); pad_right <- ceiling(pad_total / 2)
  cat(UL, HR, UR, "\n", VL, strrep(" ", pad_left), header_text, strrep(" ", pad_right), VL, "\n", LL, HR, LR, "\n", sep = "")

  cat(x$type, "\n", sep = "")
  cat(line, "Hypotheses:\n", line, sep = "")

  #### Hypotheses function for showing parameter space
  print_hypothesis <- function(es, rope = x$ROPE, alt = x$alternative) {
    # Determine the correct null value
    null_val <- if (es %in% c(delta, f2)) 0 else x$h0

    # the parameter space for interval Bayes Factor
    shift <- function(val) if (es %in% c(rho, theta)) val + x$h0 else val


    # f-test is a special case since the alternative hypothesis is fixed
    if (es == f2) {
      if (is.null(rope)) {
        cat("  ", H0, " (Null)         : ", es, " = 0\n", sep = "")
        cat("  ", H1, " (Alternative)  : ", es, " > 0\n", sep = "")
      } else {
        cat("  ", H0, " (Null)         : 0 <= ", es, " <= ", rope, "\n", sep = "")
        cat("  ", H1, " (Alternative)  : ", es, " > ", rope, "\n", sep = "")
      }
    } else {
      # Print null-value line for rho/theta only when no ROPE
      #  if (es %in% c(rho, theta) && is.null(rope))
      #  cat("  Null value        : ", es, sub0, " = ", null_val, "\n", sep = "")
      # it is removed for now

      if (is.null(rope)) {
        alt_map <- list(
          "two.sided" = paste(es, neq, null_val),
          "greater"  = paste(es, ">", null_val),
          "less" = paste(es, "<", null_val)
        )
        cat("  ", H0, " (Null)         : ", es, " = ", null_val, "\n", sep = "")
        cat("  ", H1, " (Alternative)  : ", alt_map[[alt]], "\n", sep = "")
      } else {
        lower <- shift(min(rope)); upper <- shift(max(rope))
        if (alt == "two.sided") {
          cat("  ", H0, " (Null)         : ", lower, " ", leq, " ", es, " ", leq, " ", upper, "\n", sep = "")
          cat("  ", H1, " (Alternative)  : ", es, " < ", lower, " ", union, " ", es, " > ", upper, "\n", sep = "")
        } else if (alt == "greater") {
          cat("  ", H0, " (Null)         : ", null_val, " ", leq, " ", es, " ", leq, " ", upper, "\n", sep = "")
          cat("  ", H1, " (Alternative)  : ", es, " > ", upper, "\n", sep = "")
        } else if (alt == "less") {
          cat("  ", H0, " (Null)         : ", lower, " ", leq, " ", es, " ", leq, " ", null_val, "\n", sep = "")
          cat("  ", H1, " (Alternative)  : ", es, " < ", lower, "\n", sep = "")
        }
      }
    }
  }
  if (effect_size %in% c(delta, rho, theta, f2)) print_hypothesis(effect_size)

  # Two-proportion hypothesis
  if (x$type == "Two-proportions") {
    theta0 <- paste0(theta, sub0); theta1 <- paste0(theta, sub1); theta2 <- paste0(theta, sub2)
    cat("  H", sub0, " (Null)         : ", theta1, " = ", theta2, " = ", theta0, "\n", sep = "")
    cat("  H", sub1, " (Alternative)  : ", theta1, " ", neq, " ", theta2, "\n", sep = "")
  }

  # Predictors for f2
  if (effect_size == f2) {
    cat(line, "Number of predictors:\n", line,
        "  p (reduced model) : ", x$p, "\n",
        "  k (full model)    : ", x$k, "\n", sep = "")
  }

  #### Prior density function section ####
  cat(line, "Analysis/design prior: \n", line, sep = "")

  print_prior <- function(prior_obj, es, label, type = "analysis") {

    # --- Determine header ---
    if (label == H0) {
      header <- paste0("Analysis/design prior under ", label)
    } else {
      header <- switch(type,
                       "analysis" = paste0("Analysis prior under ", label),
                       "design"   = paste0("Design prior under ", label),
                       paste0("Prior under ", label))
    }
    cat(header, ":\n", sep = "")

    # --- H0 special case with ROPE NULL ---
    if (label == H0 && is.null(x$ROPE)) {
      loc <- if (es %in% c(delta, f2)) 0 else x$h0
      cat("  Point prior (location = ", loc, ")\n", sep = "")
      return()
    }

    # --- If prior_obj$prior is NULL (whether design and analysis are the same) ---
    if (is.null(prior_obj$prior)) {
      loc <- if (es == f2) prior_obj$f_m else prior_obj$location
      cat("  Point prior (location = ", loc, ")\n", sep = "")
      return()
    }

    # --- Standard prior printing ---
    switch(prior_obj$prior,
           "Point" = if (es == f2){
             cat("  Point (",es," = ", prior_obj$f_m^2 , ")\n", sep = "")
           }else{
             cat("  Point (location = ", prior_obj$location, ")\n", sep = "")
           },
           "Normal" = cat("  Normal (location = ", prior_obj$location, ", scale = ", prior_obj$scale, ")\n", sep = ""),
           "t-distribution" = cat("  t-distribution (location = ", prior_obj$location, ", scale = ", prior_obj$scale, ", df = ", prior_obj$dff, ")\n", sep = ""),
           "d_beta" = cat("  Default Stretched Beta (k = ", prior_obj$k, ")\n", sep = ""),
           "beta" = cat("  Stretched Beta (alpha = ", prior_obj$alpha, ", beta = ", prior_obj$beta, ")\n", sep = ""),
           "Moment" = {
             if (es == f2)
               cat("  Moment prior (", es, " = ", prior_obj$f_m^2, ", df = ", prior_obj$dff, ")\n", sep = "")
             else
               cat("  Normal-moment (location = ", prior_obj$location, ", scale = ", prior_obj$scale, ")\n", sep = "")
           },
           "effectsize" = cat("  Effect size prior (scale = ", prior_obj$rscale, ", ", es, " = ", prior_obj$f_m^2, ", df = ", prior_obj$dff, ")\n", sep = "")
    )
  }

  if (x$type != "Two-proportions") {
    # H0
    print_prior(x$analysis_h1, effect_size, H0, type = "analysis")

    # H1
    print_prior(x$analysis_h1, effect_size, H1, type = "analysis")

    if (is.null(x$design_h1$prior)){ print_prior(x$analysis_h1, effect_size, H1, type = "design")} else{
      print_prior(x$design_h1, effect_size, H1, type = "design")
    }
  } else {
    # Two-proportion priors
    theta0 <- paste0(theta, sub0); theta1 <- paste0(theta, sub1); theta2 <- paste0(theta, sub2)
    cat("Analysis/design prior under H", sub0, "\n  ", theta0, " ~ Beta(alpha = ", x$analysis_h0$a, ", beta = ", x$analysis_h0$b, ")\n", sep = "")
    cat("Analysis prior under H", sub1, "\n  ", theta1, " ~ Beta(alpha = ", x$analysis_h1_theta_1$a, ", beta = ", x$analysis_h1_theta_1$b, ")\n  ", theta2, " ~ Beta(alpha = ", x$analysis_h1_theta_2$a, ", beta = ", x$analysis_h1_theta_2$b, ")\n", sep = "")


    cat("Design prior under H", sub1, "\n", sep = "")
    if (x$design_h1_theta_1$prior == "same") {
      cat("  ", theta1, " ~ Beta(alpha = ", x$analysis_h1_theta_1$a, ", beta = ", x$analysis_h1_theta_2$b, ")\n", sep = "")
    }
    if (x$design_h1_theta_2$prior == "same") {
      cat("  ", theta2, " ~ Beta(alpha = ", x$analysis_h1_theta_2$a, ", beta = ", x$analysis_h1_theta_2$b, ")\n", sep = "")
    }
    if (x$design_h1_theta_1$prior == "beta") {
      cat("  ", theta1, " ~ Beta(alpha = ", x$design_h1_theta_1$a, ", beta = ", x$design_h1_theta_1$b, ")\n", sep = "")

    }
    if (x$design_h1_theta_2$prior == "beta") {
      cat("  ", theta2, " ~ Beta(alpha = ", x$design_h1_theta_2$a, ", beta = ", x$design_h1_theta_2$b, ")\n", sep = "")

    }
    if (x$design_h1_theta_1$prior == "Point") {
      cat("  ", theta1, " = ", x$design_h1_theta_1$p, "\n", sep = "")

    }
    if (x$design_h1_theta_2$prior == "Point") {
      cat("  ", theta2, " = ", x$design_h1_theta_2$p, "\n", sep = "")
    }

  }

  cat(line, "Results:\n", line, sep = "")
  cat(paste0("  True Positive Rate                  = ", round(x$results[1], digits), "\n"))
  cat(paste0("  False Positive Rate                 = ", round(x$results[4], digits), "\n"))
  cat(paste0("  True Negative Rate                  = ", round(x$results[3], digits), "\n"))
  cat(paste0("  False Negative Rate                 = ", round(x$results[2], digits), "\n"))

  # Sample sizes
  if (!(x$type %in% c("Two-proportions", "Independent-samples t-test (equal variance)"))) {
    cat("  Required Sample size                = ", round(unlist(x$results[5]), 1), "  <---\n", sep = "")
  } else {
    cat("  Required Sample size Group 1        = ", round(unlist(x$results[5]), 1), "  <---\n", sep = "")
    cat("  Required Sample size Group 2        = ", round(unlist(x$results[6]), 1), "  <---\n", sep = "")
  }

  cat("  Threshold of compelling evidence    = ", x$threshold, "\n", sep = "")
  cat(line)
}


#' Print Method for BFvalue Objects
#'
#' Displays the results of a \code{"BFvalue"} object.
#'
#' This method prints key results from a Bayesian test, including the
#' Bayes factor and relevant test statistics with frequentist test result. The object can be generated
#' by any of the following functions:
#' \code{\link{BF10.ttest.OneSample}}, \code{\link{BF10.ttest.TwoSample}}, \code{\link{BF10.cor}}, \code{\link{BFpower.f.test}} \code{\link{BF10.bin.test}}, or \code{\link{BF10.props}}.
#'
#' @param x A \code{"BFvalue"} object returned by one of the BF10 testing functions listed in Details.
#' @param ... Additional arguments (currently unused; included for method consistency).
#'
#' @return Invisibly returns the input \code{"BFvalue"} object.
#'
#' @export
#' @method print BFvalue
#'
#' @examples
#' result <- BF10.ttest.OneSample(
#'  tval = 2,
#'  df = 50,
#'  prior_analysis = "t-distribution",
#'  location = 0,
#'  scale = 0.707,
#'  dff = 1,
#'  alternative = "two.sided")
#' print(result)
print.BFvalue <- function(x, ...) {

  #### Symbols
  UL <- "\u2554"; UR <- "\u2557"; LL <- "\u255a"; LR <- "\u255d"
  HL <- "\u2550"; VL <- "\u2551"; HR <- strrep(HL, 50)
  line <- paste0("\u2500", strrep("\u2500", 50), "\n")
  digits <- 3

  # Subscripts
  sub0 <- "\u2080"; sub1 <- "\u2081"; sub2 <- "\u2082"
  H0 <- paste0("H", sub0); H1 <- paste0("H", sub1)
  delta <- "\u03b4"; rho <- "\u03c1"; f2 <- "f\u00B2"; theta <- "\u03b8"
  neq <- "\u2260"; leq <- "\u2264"; union <- "\u222a"

  # Bayes Factor subscripts
  BF10 <- "BF\u2081\u2080"
  BF01 <- "BF\u2080\u2081"

  # Effect size symbol
  effect_size <- switch(x$type,
                        "One-sample t-test" = delta,
                        "Independent-samples t-test (equal variance)" = delta,
                        "Correlation" = rho,
                        "Regression/ANOVA" = f2,
                        "One-proportion" = theta,
                        "Two-proportions" = 0 )

  # Centered header
  header_text <- "BAYES FACTOR CALCULATION"
  pad_total <- 50 - nchar(header_text)
  pad_left <- floor(pad_total / 2); pad_right <- ceiling(pad_total / 2)
  cat(UL, HR, UR, "\n", VL, strrep(" ", pad_left), header_text, strrep(" ", pad_right), VL, "\n", LL, HR, LR, "\n", sep = "")

  cat(x$type, "\n", sep = "")
  cat(line, "Hypotheses:\n", line, sep = "")

  #### Hypotheses function
  print_hypothesis <- function(es, rope = x$ROPE, alt = x$alternative) {
    # Determine the correct null value
    null_val <- if (es %in% c(delta, f2)) 0 else x$h0
    shift <- function(val) if (es %in% c(rho, theta)) val + x$h0 else val

    if (es == f2) {
      if (is.null(rope)) {
        cat("  ", H0, " (Null)         : ", es, " = 0\n", sep = "")
        cat("  ", H1, " (Alternative)  : ", es, " > 0\n", sep = "")
      } else {
        cat("  ", H0, " (Null)         : 0 <= ", es, " <= ", rope, "\n", sep = "")
        cat("  ", H1, " (Alternative)  : ", es, " > ", rope, "\n", sep = "")
      }
    } else {
      # Print null-value line for rho/theta only when no ROPE
      #if (es %in% c(rho, theta) && is.null(rope))
      #  cat("  Null value        : ", es, sub0, " = ", null_val, "\n", sep = "")

      if (is.null(rope)) {
        alt_map <- list(
          "two.sided" = paste(es, neq, null_val),
          "greater"  = paste(es, ">", null_val),
          "less" = paste(es, "<", null_val)
        )
        cat("  ", H0, " (Null)         : ", es, " = ", null_val, "\n", sep = "")
        cat("  ", H1, " (Alternative)  : ", alt_map[[alt]], "\n", sep = "")
      } else {
        lower <- shift(min(rope)); upper <- shift(max(rope))
        if (alt == "two.sided") {
          cat("  ", H0, " (Null)         : ", lower, " ", leq, " ", es, " ", leq, " ", upper, "\n", sep = "")
          cat("  ", H1, " (Alternative)  : ", es, " < ", lower, " ", union, " ", es, " > ", upper, "\n", sep = "")
        } else if (alt == "greater") {
          cat("  ", H0, " (Null)         : ", null_val, " ", leq, " ", es, " ", leq, " ", upper, "\n", sep = "")
          cat("  ", H1, " (Alternative)  : ", es, " > ", upper, "\n", sep = "")
        } else if (alt == "less") {
          cat("  ", H0, " (Null)         : ", lower, " ", leq, " ", es, " ", leq, " ", null_val, "\n", sep = "")
          cat("  ", H1, " (Alternative)  : ", es, " < ", lower, "\n", sep = "")
        }
      }
    }
  }
  if (effect_size %in% c(delta, rho, theta, f2)) print_hypothesis(effect_size)

  # Two-proportion hypothesis
  if (x$type == "Two-proportions") {
    theta0 <- paste0(theta, sub0); theta1 <- paste0(theta, sub1); theta2 <- paste0(theta, sub2)
    cat("  H", sub0, " (Null)         : ", theta1, " = ", theta2, " = ", theta0, "\n", sep = "")
    cat("  H", sub1, " (Alternative)  : ", theta1, " ", neq, " ", theta2, "\n", sep = "")
  }


  #### Prior density function section ####
  cat(line, "Analysis prior: \n", line, sep = "")

  print_prior <- function(prior_obj, es, label, type = "analysis") {

    # --- Determine header ---
    header <- paste0("Analysis prior under ", label)


    cat(header, ":\n", sep = "")

    # --- H0 special case with ROPE NULL ---
    if (label == H0 && is.null(x$ROPE)) {
      loc <- if (es %in% c(delta, f2)) 0 else x$h0
      cat("  Point prior (location = ", loc, ")\n", sep = "")
      return()
    }



    # --- Standard prior printing ---
    switch(prior_obj$prior,
           "Point" = cat("  Point (location = ", if (es == f2) prior_obj$f_m^2 else prior_obj$location, ")\n", sep = ""),
           "Normal" = cat("  Normal (location = ", prior_obj$location, ", scale = ", prior_obj$scale, ")\n", sep = ""),
           "t-distribution" = cat("  t-distribution (location = ", prior_obj$location, ", scale = ", prior_obj$scale, ", df = ", prior_obj$dff, ")\n", sep = ""),
           "d_beta" = cat("  Default Stretched Beta (k = ", prior_obj$k, ")\n", sep = ""),
           "beta" = cat("  Stretched Beta (alpha = ", prior_obj$alpha, ", beta = ", prior_obj$beta, ")\n", sep = ""),
           "Moment" = {
             if (es == f2)
               cat("  Moment prior (", es, " = ", prior_obj$f_m^2, ", df = ", prior_obj$dff, ")\n", sep = "")
             else
               cat("  Normal-moment (location = ", prior_obj$location, ", scale = ", prior_obj$scale, ")\n", sep = "")
           },
           "effectsize" = cat("  Effect size prior (scale = ", prior_obj$rscale, ", ", es, " = ", prior_obj$f_m^2, ", df = ", prior_obj$dff, ")\n", sep = "")
    )
  }

  if (x$type != "Two-proportions") {
    # H0
    print_prior(x$analysis_h1, effect_size, H0, type = "analysis")
    # H1
    print_prior(x$analysis_h1, effect_size, H1, type = "analysis")

  } else {
    # Prior under H0
    cat("Analysis prior under H", sub0, "\n", sep = "")
    cat(" ", theta0, " ~ Beta(alpha = ", x$analysis_h0$a,
        ", beta = ", x$analysis_h0$b, ")\n", sep = "")

    # Prior under H1
    cat("Analysis prior under H", sub1, "\n", sep = "")
    cat(" ", theta1, " ~ Beta(alpha = ", x$analysis_h1_theta_1$a,
        ", beta = ", x$analysis_h1_theta_1$b, ")\n", sep = "")
    cat(" ", theta2, " ~ Beta(alpha = ", x$analysis_h1_theta_2$a,
        ", beta = ", x$analysis_h1_theta_2$b, ")\n", sep = "")

  }

  ######### Results

  cat(line)
  cat("Results:\n")
  cat(line)

  if (effect_size == delta) {
    cat(
      "  t(df=", x$df, ") = ", x$tval,
      ", p = ", x$p.value,
      ", d = ", x$d,
      ",\n  ", BF10, " = ", x$bf10,
      ", ", BF01, " = ", 1 / x$bf10, "\n", sep = ""
    )

    if (x$type == "Independent-samples t-test (equal variance)") {
      cat("  N1 = ", x$N1, ", N2 = ", x$N2, "\n", sep = "")
    }

  } else if (effect_size == rho) {
    cat(
      "  r (n = ", x$n, ") = ", x$r,
      ", p = ", x$p.value,
      ",\n  BF\u2081\u2080 = ", x$bf10,
      ", BF\u2080\u2081 = ", 1 / x$bf10, "\n", sep = ""
    )

  } else if (effect_size == f2) {
    cat(
      "  F(df", sub1, " = ", x$df1, ", df", sub2, " = ", x$df2, ") = ", x$fval,
      ", p = ", x$p.value,
      ",\n  ", BF10, " = ", x$bf10,
      ", ", BF01, " = ", 1 / x$bf10, "\n", sep = ""
    )

  } else if (effect_size == theta) {
    cat(
      "  n = ", x$n, ", x = ", x$x,
      ", p = ", x$p.value,
      ",\n  BF", sub1, sub0, " = ", x$bf10,
      ", BF", sub0, sub1, " = ", 1 / x$bf10, "\n", sep = ""
    )
  }

  # Two-proportions special case
  if (x$type == "Two-proportions") {
    cat(
      "  n", sub1, " = ", x$N1, ", x", sub1, " = ", x$x1,
      ", n", sub2, " = ", x$N2, ", x", sub2, " = ", x$x2,
      ",\n  Odds Ratio = ", x$OddRatio,
      ", p = ", x$p.value, "\n", sep = ""
    )
    cat(
      "  BF", sub1, sub0, " = ", x$bf10,
      ", BF", sub0, sub1, " = ", 1 / x$bf10, "\n", sep = ""
    )
  }

  cat(line)
}


#' Plot Method for BFpower Objects
#'
#' Visualizes a \code{"BFpower"} object.
#'
#' This plot method can return up to three plots (or five plots for testing two-proportions) based on the information
#' from the \code{"BFpower"} object:
#'   \itemize{
#'     \item The first plot displays the analysis prior and the design prior. However, for \code{\link{BFpower.props}}, three plots are returned, corresponding to the three thetas.
#'     \item The second plot contains two panels where the left panel shows the
#'       true and false positive rates as a function of sample size, and the
#'       right panel shows the true and false negative rates.
#'     \item The third plot illustrates the relationship between the data
#'       and the Bayes factors.
#'   }
#'
#' The object can be generated by any of the following functions:
#' \code{\link{BF10.ttest.OneSample}}, \code{\link{BF10.ttest.TwoSample}}, \code{\link{BF10.cor}}, \code{\link{BFpower.f.test}} \code{\link{BF10.bin.test}}, or \code{\link{BF10.props}}.
#'
#'
#' @param x A \code{"BFpower"} object returned by one of the BFpower functions listed in the section Details.
#' @param plot_power Logical. If \code{TRUE}, the power-related plots are returned.
#' @param plot_rel Logical. If \code{TRUE}, the plot showing the relationship between the data and the Bayes factors is returned.
#' @param ... Additional arguments (currently unused; included for method consistency).
#'
#' @return A list of up to three \code{ggplot} objects.
#'
#' @export
#' @method plot BFpower
#'
#' @examples
#' results <- BFpower.cor(
#'   alternative = "greater",
#'   h0 = 0,
#'   threshold = 3,
#'   true_rate = 0.8,
#'   false_rate = 0.05,
#'   prior_analysis = "beta",
#'   alpha = 1,
#'   beta = 1,
#'   prior_design = "Point",
#'   location_d = 0.3
#' )
#' print(results)
#' plot(results, plot_power = TRUE, plot_rel = TRUE)
plot.BFpower <- function(x, plot_power = FALSE, plot_rel = FALSE,...) {

  de_an_prior <- if (is.null(x$design_h1$prior)) 1 else 0

  # Initialize list to store plots
  plots <- list()

  # ---- Switch by analysis type ----
  switch(x$type,

         "One-sample t-test" = {
           plots$prior <- if (is.null(x$ROPE)) {
             t1_prior_plot(
               x$analysis_h1$prior, x$analysis_h1$location, x$analysis_h1$scale, x$analysis_h1$dff,
               x$alternative,
               x$design_h1$prior, x$design_h1$location, x$design_h1$scale, x$design_h1$dff,
               de_an_prior
             )
           } else {
             t1e_prior_plot(
               x$analysis_h1$prior, x$analysis_h1$location, x$analysis_h1$scale, x$analysis_h1$dff,
               x$alternative, x$ROPE,
               de_an_prior, x$design_h1$prior, x$design_h1$scale, x$design_h1$dff, x$design_h1$location
             )
           }

           if (plot_power) {
             plots$power <- if (is.null(x$ROPE)) {suppressWarnings(
               Power_t1(
                 x$threshold, x$analysis_h1$prior, x$analysis_h1$location, x$analysis_h1$scale, x$analysis_h1$dff,
                 x$alternative, x$design_h1$prior, x$design_h1$location, x$design_h1$scale, x$design_h1$dff,
                 de_an_prior, unlist(x$results[5])
               ))
             } else {suppressWarnings(
               Power_t1e(
                 x$threshold, x$analysis_h1$prior, x$analysis_h1$location, x$analysis_h1$scale, x$analysis_h1$dff,
                 x$alternative, x$design_h1$prior, x$design_h1$location, x$design_h1$scale, x$design_h1$dff,
                 de_an_prior, unlist(x$results[5]), x$ROPE
               ))
             }
           }

           if (plot_rel) {
             plots$relative <- if (is.null(x$ROPE)) {suppressWarnings(
               bf10_t1(
                 x$threshold, unlist(x$result[5]) - 1,
                 x$analysis_h1$prior, x$analysis_h1$location, x$analysis_h1$scale, x$analysis_h1$dff,
                 x$alternative
               ))
             } else {suppressWarnings(
               te1_BF(
                 x$threshold, unlist(x$result[5]) - 1,
                 x$analysis_h1$prior, x$analysis_h1$location, x$analysis_h1$scale, x$analysis_h1$dff,
                 x$alternative, x$ROPE
               ))
             }
           }
         },

         "Independent-samples t-test (equal variance)" = {
           plots$prior <- if (is.null(x$ROPE)) {
             t1_prior_plot(
               x$analysis_h1$prior, x$analysis_h1$location, x$analysis_h1$scale, x$analysis_h1$dff,
               x$alternative,
               x$design_h1$prior, x$design_h1$location, x$design_h1$scale, x$design_h1$dff,
               de_an_prior
             )
           } else {
             t1e_prior_plot(
               x$analysis_h1$prior, x$analysis_h1$location, x$analysis_h1$scale, x$analysis_h1$dff,
               x$alternative, x$ROPE,
               de_an_prior, x$design_h1$prior, x$design_h1$scale, x$design_h1$dff, x$design_h1$location
             )
           }

           if (plot_power) {
             plots$power <- if (is.null(x$ROPE)) {suppressWarnings(
               Power_t2(
                 x$threshold, x$analysis_h1$prior, x$analysis_h1$location, x$analysis_h1$scale, x$analysis_h1$dff,
                 x$alternative, x$design_h1$prior, x$design_h1$location, x$design_h1$scale, x$design_h1$dff,
                 de_an_prior, x$results[1,5], x$results[1,6]/x$results[1,5]
               ))
             } else {suppressWarnings(
               Power_t2e(
                 x$threshold, x$analysis_h1$prior, x$analysis_h1$location, x$analysis_h1$scale, x$analysis_h1$dff,
                 x$alternative, x$design_h1$prior, x$design_h1$location, x$design_h1$scale, x$design_h1$dff,
                 de_an_prior, x$results[1,5], x$results[1,6]/x$results[1,5], x$ROPE
               ))
             }
           }

           if (plot_rel) {
             plots$relative <- if (is.null(x$ROPE)) {suppressWarnings(
               t2_BF(
                 x$threshold, x$result[1,5], x$results[1,6]/x$results[1,5], 0,
                 x$analysis_h1$prior, x$analysis_h1$location, x$analysis_h1$scale, x$analysis_h1$dff, x$alternative
               ))
             } else {suppressWarnings(
               t2e_BF(
                 x$threshold, x$result[1,5], x$results[1,6]/x$results[1,5],
                 x$analysis_h1$prior, x$analysis_h1$location, x$analysis_h1$scale, x$analysis_h1$dff,
                 x$alternative, x$ROPE
               ))
             }
           }
         },

         "Correlation" = {
           plots$prior <- if (is.null(x$ROPE)) {
             r_prior_plot(
               x$analysis_h1$k, x$analysis_h1$alpha, x$analysis_h1$beta,
               x$h0, x$h0, x$analysis_h1$scale,
               1, x$analysis_h1$prior, de_an_prior,
               x$design_h1$k, x$design_h1$alpha, x$design_h1$beta,
               x$design_h1$location, x$design_h1$scale, 1,
               x$design_h1$prior, x$alternative
             )
           } else {
             re_prior_plot(
               x$analysis_h1$k, x$analysis_h1$alpha, x$analysis_h1$beta,
               x$h0, x$h0, x$analysis_h1$scale,
               1, x$analysis_h1$prior, de_an_prior,
               x$design_h1$k, x$design_h1$alpha, x$design_h1$beta,
               x$design_h1$location, x$design_h1$scale, 1,
               x$design_h1$prior, x$alternative, x$ROPE
             )
           }

           if (plot_power) {
             plots$power <- if (is.null(x$ROPE)) {
               Power_r(
                 x$threshold, x$analysis_h1$k, x$analysis_h1$alpha,
                 x$analysis_h1$beta, x$h0, x$alternative,
                 x$h0, x$analysis_h1$scale, x$analysis_h1$dff, x$analysis_h1$prior,
                 x$design_h1$k, x$design_h1$alpha, x$design_h1$beta,
                 x$design_h1$location, x$design_h1$scale, 1, x$design_h1$prior,
                 de_an_prior, x$results[1,5]
               )
             } else {
               Power_re(
                 x$threshold, x$analysis_h1$k, x$analysis_h1$alpha,
                 x$analysis_h1$beta, x$h0, x$alternative,
                 x$h0, x$analysis_h1$scale, x$analysis_h1$dff, x$analysis_h1$prior,
                 x$design_h1$k, x$design_h1$alpha, x$design_h1$beta,
                 x$design_h1$location, x$design_h1$scale, 1, x$design_h1$prior,
                 de_an_prior, x$results[1,5], x$ROPE
               )
             }
           }

           if (plot_rel) {
             plots$relative <- if (is.null(x$ROPE)) {
               r_bf10_p(
                 x$threshold, x$results[1,5], x$analysis_h1$k, x$analysis_h1$alpha, x$analysis_h1$beta,
                 x$h0, x$alternative, x$h0, x$analysis_h1$scale, 1, x$analysis_h1$prior
               )
             } else {
               re_bf10_p(
                 x$threshold, x$results[1,5], x$analysis_h1$k, x$analysis_h1$alpha, x$analysis_h1$beta,
                 x$h0, x$alternative, x$h0, x$analysis_h1$scale, 1, x$analysis_h1$prior, x$ROPE
               )
             }
           }
         },

         "Regression/ANOVA" = {
           q <- x$k - x$p
           plots$prior <- if (is.null(x$ROPE)) {
             prior_plot_f(
               q, x$analysis_h1$dff, x$analysis_h1$rscale, x$analysis_h1$f_m, x$analysis_h1$prior,
               x$design_h1$dff, x$design_h1$rscale, x$design_h1$f_m, x$design_h1$prior, de_an_prior
             )
           } else {
             prior_plot_fe(
               q, x$analysis_h1$dff, x$analysis_h1$rscale, x$analysis_h1$f_m, x$analysis_h1$prior,
               x$design_h1$dff, x$design_h1$rscale, x$analysis_h1$f_m, x$design_h1$prior, de_an_prior, x$ROPE
             )
           }

           if (plot_power) {
             plots$power <- if (is.null(x$ROPE)) {
               Power_f(
                 x$threshold, x$k, x$p, x$analysis_h1$dff, x$analysis_h1$rscale, x$analysis_h1$f_m, x$analysis_h1$prior,
                 1, 1, x$design_h1$dff, x$design_h1$rscale, x$design_h1$f_m, x$design_h1$prior, de_an_prior,
                 unlist(x$result[1,5])
               )
             } else {
               Power_fe(
                 x$threshold, x$k, x$p, x$analysis_h1$dff, x$analysis_h1$rscale, x$analysis_h1$f_m, x$analysis_h1$prior,
                 1, 1, x$design_h1$dff, x$design_h1$rscale, x$design_h1$f_m, x$design_h1$prior, de_an_prior,
                 unlist(x$result[1,5]), x$ROPE
               )
             }
           }

           if (plot_rel) {
             plots$relative <- if (is.null(x$ROPE)) {
               bf10_f(x$threshold, unlist(x$result[1,5]), x$k, x$p, x$analysis_h1$dff,
                      x$analysis_h1$rscale, x$analysis_h1$f_m, x$analysis_h1$prior)
             } else {
               bf10_fe(x$threshold, unlist(x$result[1,5]), x$k, x$p, x$analysis_h1$dff,
                       x$analysis_h1$rscale, x$analysis_h1$f_m, x$analysis_h1$prior, x$ROPE)
             }
           }
         },

         "One proportion" = {
           plots$prior <- if (is.null(x$ROPE)) {
             bin_prior_plot(
               x$h0, x$analysis_h1$alpha, x$analysis_h1$beta, x$h0, x$analysis_h1$scale, x$analysis_h1$prior,
               x$design_h1$alpha, x$design_h1$beta, x$design_h1$location,
               x$design_h1$scale, x$design_h1$prior,
               x$alternative, de_an_prior
             )
           } else {
             bin_e_prior_plot(
               x$h0, x$analysis_h1$alpha, x$analysis_h1$beta, x$h0, x$analysis_h1$scale, x$analysis_h1$prior,
               x$design_h1$alpha, x$design_h1$beta, x$design_h1$location,
               x$design_h1$scale, x$design_h1$prior,
               x$alternative, de_an_prior, x$ROPE
             )
           }

           if (plot_power) {
             plots$power <- if (is.null(x$ROPE)) {
               Power_bin(
                 x$threshold, x$h0, x$analysis_h1$alpha, x$analysis_h1$beta,
                 x$h0, x$analysis_h1$scale, x$analysis_h1$prior,
                 x$alternative,
                 x$design_h1$alpha, x$design_h1$beta, x$design_h1$location,
                 x$design_h1$scale, x$design_h1$prior, de_an_prior,
                 unlist(x$results[1,5])
               )
             } else {
               Power_e_bin(
                 x$threshold, x$h0, x$analysis_h1$alpha, x$analysis_h1$beta,
                 x$h0, x$analysis_h1$scale, x$analysis_h1$prior,
                 x$alternative,
                 x$design_h1$alpha, x$design_h1$beta, x$design_h1$location,
                 x$design_h1$scale, x$design_h1$prior, de_an_prior,
                 unlist(x$results[1,5]), x$ROPE
               )
             }
           }

           if (plot_rel) {
             plots$relative <- if (is.null(x$ROPE)) {
               bin_bf10(
                 x$threshold, unlist(x$results[1,5]), x$analysis_h1$alpha,
                 x$analysis_h1$beta, x$h0, x$analysis_h1$scale, x$analysis_h1$prior,
                 x$alternative
               )
             } else {
               bin_e_bf10(
                 x$threshold, unlist(x$results[1,5]), x$analysis_h1$alpha,
                 x$analysis_h1$beta, x$h0, x$analysis_h1$scale, x$analysis_h1$prior,
                 x$alternative, x$ROPE
               )
             }
           }
         },

         "Two-proportions" = {
           # Prior plotting
           plots$prior0 <- p2_prior_plot(x$analysis_h0$a, x$analysis_h0$b, 1, 1, 0, "same", 0)
           plots$prior1 <- p2_prior_plot(x$analysis_h1_theta_1$a, x$analysis_h1_theta_1$b,
                                         x$design_h1_theta_1$a, x$design_h1_theta_1$b,
                                         x$design_h1_theta_1$p, x$design_h1_theta_1$prior, 1)
           plots$prior2 <- p2_prior_plot(x$analysis_h1_theta_2$a, x$analysis_h1_theta_2$b,
                                         x$design_h1_theta_2$a, x$design_h1_theta_2$b,
                                         x$design_h1_theta_2$p, x$design_h1_theta_2$prior, 2)

           if (plot_power) {
             plots$power <- Power_p2(
               x$threshold, unlist(x$results[1,5]), x$analysis_h0$a, x$analysis_h0$b,
               x$analysis_h1_theta_1$a, x$analysis_h1_theta_1$b,
               x$analysis_h1_theta_2$a, x$analysis_h1_theta_2$b,
               unlist(x$results[1,6]) / unlist(x$results[1,5]),
               x$design_h1_theta_1$prior, x$design_h1_theta_1$a, x$design_h1_theta_1$b,
               x$design_h1_theta_1$p,
               x$design_h1_theta_2$prior, x$design_h1_theta_2$a, x$design_h1_theta_2$b,
               x$design_h1_theta_2$p
             )
           }

           if (plot_rel) {
             plots$relative <- heatmap_p2(x$grid, x$threshold)
           }
         },

  )

  # Always print the first plot
  if(x$type != "Two-proportions"){
    print(plots$prior)
    } else{
    print(plots$prior0)
    print(plots$prior1)
    print(plots$prior2)

  }

  # Conditionally print the other plots
  if(plot_power) print(plots$power)
  if(plot_rel) print(plots$relative)

  return(invisible(plots))
}
